name: "Tests"
permissions:
    contents: read
on:
    push:
        branches: ["latest"]
        paths:
            - src/**
            - tests/**
            - Cargo.toml
            - Cargo.lock
            - .rustfmt.toml
            - .github/workflows/test.yml
    pull_request:
        branches: ["latest"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always
    SCCACHE_GHA_ENABLED: "true"
    RUSTC_WRAPPER: "sccache"

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false

            - name: sccache-cache
              uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

            - name: Install Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17
              with:
                  toolchain: stable, nightly
                  components: rustfmt, clippy
                  cache-directories: |
                      ~/.cargo/registry
                      ~/.cargo/bin
                      target

            - name: Install cargo-nextest
              shell: bash
              run: |
                  if [[ -z $(which cargo-nextest) ]]; then
                    curl -sL https://get.nexte.st/latest/linux -o nextest.tgz
                    tar xfz nextest.tgz
                    mv cargo-nextest /home/runner/.cargo/bin
                  fi

            - name: check formatting
              run: cargo +nightly fmt --check --all

            - name: run the tests
              run: cargo nextest run --all-targets --all-features --future-incompat-report

            - name: consult Clippy
              run: cargo +stable clippy --all-targets --all-features -- -D warnings
